### ISSUE TITLE
instance-manager strips out user permissions from aws-auth configmap

### ISSUE THREAD

**Issue by eytan-avisror** [orkaproj/instance-manager#26]
Looks like instance-manager is stripping out user permissions from aws-auth configmap.
For example, given a configmap:
```
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::1234567890:role/a-valid-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::1234567890:role/an-invalid-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::1234567890:role/a-valid-user
      username:  user:some-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
  name: aws-auth
  namespace: kube-system
```

After reconciling, instance-manager will strip out last two mapRoles.
We should have some mechanism of **NOT** stripping out user access, possibly we can look at `.username` if it starts with `user:` and as a result not touch it.

**Comment by eytan-avisror** [comment]
Solution:
- Discover active ARNs from controller configmap & tagged CF stacks
- If existing configmap has a role that conflicts with discovered configmap, override it from the discovered ARNs as a **node role**, for example if ['arn-1', 'arn-2'] were discovered, and configmap was:
```
data:
  mapRoles: |
    - rolearn: arn:aws:iam::0000000000:role/arn-1
      username: user:some-user
      groups:
        - system:masters
```
It will be removed, and replaced with the node mapRole.
```
data:
  mapRoles: |
    - rolearn: arn:aws:iam::0000000000:role/arn-1
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:bootstrappers
      - system:nodes
```

- If existing configmap has a role that does not conflict with discovered ARNs, we add it as is in addition to discovered ARNs.
